Repository mattyparty/IntelliSup, pull requests merged in 2021-01, with the labels that each got.

#19 had to tweak the data model and changed the seed files a bit
  database/seeds.sql
  models/index.js
  models/openpos.js
  models/supplier.js
  package-lock.json
  package.json
  public/js/tabulator.js
  routes/api/index.js
Labels: back end

#22 code israel and matt worked on
  public/js/tabulator.js
  routes/api/index.js
  views/index.handlebars
Labels: back end

#24 Updates to Table Names & Fields
  config/passport.js
  database/seeds.sql
  models/order.js
  models/supplier.js
  models/suppliermaplogin.js
  models/user.js
  public/js/tabulator.js
  routes/api/index.js
Labels: back end

#25 Updating API route to allow user to update tracking information
  public/js/tabulator.js
  routes/api/index.js
Labels: back end

#27 Created Purchase Order Form
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#31 added navbar with logo and logout to members page
  public/css/style.css
  public/css/tabulator.min.css
  public/images/intellisup_logo.png
  public/login.html
  public/members.html
  public/signup.html
  public/stylesheets/style.css
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#34 Updated the tabulator table to use Bulma styling
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#35 Added Order Form V2 & Styling
  public/css/style.css
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#36 button formatting , pagination add, table reorder
  public/css/tabulator.minx.css
  public/js/tabulator.js
  views/partials/header.handlebars
Labels: front end

#37 updating landing page
  config/middleware/isAuthenticated.js
  package-lock.json
  package.json
  public/index.html
  public/js/signup.js
  public/login.html
  routes/api/index.js
  routes/html/index.js
Labels: front end

#38 added boiler plage for admin page, all tests passed
  routes/api/index.js
  routes/html/index.js
  views/admin.handlebars
Labels: back end, front end

#39 Cleanup files
  package.json
  public/css/tabulator.min.css
  public/css/tabulator.minx.css
  public/index.html
  public/js/account.js
  public/js/login.js
  public/js/signup.js
  public/js/tabulator.js
  public/js/tabulator.min.js
  public/signup.html
  routes/api/index.js
  routes/html/index.js
  views/.gitkeep
  views/layouts/.gitkeep
  views/layouts/main.handlebars
  views/partials/.gitkeep
Labels: back end

#41 admin page tweaks and add po tweaks
  package.json
  public/index.html
  public/js/admin.js
  public/js/tabulator.js
  routes/api/index.js
  views/admin.handlebars
  views/layouts/main.handlebars
Labels: back end

#42 Updated Handlebars & Comments
  public/js/tabulator.js
  views/admin.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/header.handlebars
Labels: back end, documentation, front end

#43 updated date format for due date on table
  public/js/tabulator.js
Labels: front end

#45 updating tables to list FK to allow update. Also updated API route to…
  models/order.js
  routes/api/index.js
Labels: back end, front end

#46 Html to handlebars
  public/index.html
  routes/api/index.js
  routes/html/index.js
  views/account.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#47 adding logic to allow supplier to be updated. Also correcting logic t…
  models/order.js
  models/supplier.js
  public/js/admin.js
  public/js/tabulator.js
  routes/api/index.js
Labels: back end

#48 adding logic to allow admin to update/change supplier number for logi…
  models/order.js
  models/supplier.js
  public/js/tabulator.js
  routes/api/index.js
Labels: back end

#49 moved purchase order form to admin page
  routes/api/index.js
  views/account.handlebars
  views/admin.handlebars
Labels: front end

#50 Navbar Updates
  routes/html/index.js
  views/account.handlebars
  views/admin.handlebars
  views/index.handlebars
  views/partials/navbar.handlebars
Labels: front end

#51 adding supplier options
  public/js/admin.js
  routes/api/index.js
Labels: back end

#55 added admin and account buttons for navigation
  routes/html/index.js
  views/partials/navbar.handlebars
Labels: front end

#57 added additional content to home page, updated CSS
  package-lock.json
  package.json
  public/css/style.css
  public/images/intellisup_homepage_icon.png
  views/admin.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
Labels: front end

#60 Made a bunch of formatting and content changes to the home page
  package-lock.json
  package.json
  public/css/style.css
  public/js/account.js
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/navbar.handlebars
Labels: front end

#61 Homepage updates
  public/css/style.css
  public/js/admin.js
  public/js/signup.js
  public/js/tabulator.js
  routes/api/index.js
  routes/html/index.js
  views/account.handlebars
  views/admin.handlebars
  views/index.handlebars
  views/partials/footer.handlebars
  views/partials/navbar.handlebars
Labels: front end

#63 final formatting updates
  public/css/style.css
  public/js/signup.js
  views/account.handlebars
  views/admin.handlebars
  views/index.handlebars
Labels: front end

#66 corrected footer sizing
  public/css/style.css
Labels: front end

#68 Cleanup comments, formatting of code, and README
  .github/workflows/deploy.yml
  README.md
  config/passport.js
  database/schema.sql
  database/seeds.sql
  database/seedsnew.sql
  models/index.js
  models/order.js
  models/supplier.js
  models/suppliermaplogin.js
  models/user.js
  public/css/style.css
  public/images/account.png
  public/images/admin.png
  public/images/homePage.png
  public/js/account.js
  public/js/admin.js
  public/js/login.js
  public/js/signup.js
  public/js/tabulator.js
  routes/api/index.js
  routes/html/index.js
  routes/index.js
  server.js
  views/account.handlebars
  views/admin.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/footer.handlebars
  views/partials/navbar.handlebars
Labels: back end, documentation, front end
